### PR TITLE
update to stop using deprecated django static files

### PR DESCRIPTION
**Pull request by saty9**
Fix for issue #1
Required in order to work with django 3.0
Sorry previous pull request was missing  a file

### CODE REVIEW

**Comment by sedrubal** [comment]
This fix works for me :wink: looking forward that this gets merged and released :wink:

**Comment by simontorres** [comment]
Same here!

**Comment by DanielSwain** [comment]
Hoping to see this PR merged, but should Django be pinned to >= 2.1?  [Reference](https://docs.djangoproject.com/en/3.0/releases/2.1/#features-deprecated-in-2-1)

**Comment by saty9** [comment]
> 
> 
> Hoping to see this PR merged, but should Django be pinned to >= 2.1? [Reference](https://docs.djangoproject.com/en/3.0/releases/2.1/#features-deprecated-in-2-1)

Thanks for that point committed an updated setup file that should pin django

**Comment by sedrubal** [comment]
@BenjjinF are you still maintaining this project or do we have to fork it?

**Comment by BenjjinF** [comment]
I'll have a go at reviewing things tomorrow. Sorry for the delay ~

**Comment by simontorres** [comment]
When will this be going to PYPI?

**Comment by BenjjinF** [comment]
I'm working on linting and a publishing pipeline right now.

**Comment by simontorres** [comment]
Awesome!! thank you very much!

**Comment by BenjjinF** [comment]
Should be good ~

**Pull request merged**
